ORDEN_CASILLAS: list[str] = [
    "OBLIGADO_DECLARAR",
    "PATRIMONIO_BRUTO", "PATRIMONIO_LIQUIDO",
    "ING_BRUTO_GENERAL", "INCR_APORTES", "INCR_CI", "INCR_TOTAL",
    "ING_NETOS_GENERAL", "COSTOS_ARRIENDOS", "CAP_40",
    "DEDUCCIONES_LIMITADAS", "EXENTA_25", "APLICADO_40", "EXTRA_LIMITE",
    "RLG_GENERAL", "RLG_PENSIONES",
    "DIV_NO_GRAVADOS", "DIV_GRAVADOS", "IMP_DIV_35",
    "BASE_TABLA_241", "IMPUESTO_241", "DESCUENTO_254_1", "DESCUENTO_DONACIONES",
    "IMPUESTO_NETO", "RETENCIONES", "ANTICIPO_SIGUIENTE", "SALDO",
]
